trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Checkout code from GitHub
- checkout: self
  displayName: 'Checkout code from GitHub'

# Step 2: Build Docker image for Django
- task: CmdLine@2
  displayName: 'Build Docker image for Django'
  inputs:
    script: docker build -t django-student .

# Step 3: Run Docker container
- task: CmdLine@2
  displayName: 'Run Docker container now'
  inputs:
    script: docker run -d -p 8000:8000 --name django-student-container django-student

# Step 4: List running Docker containers
- task: CmdLine@2
  displayName: 'List running Docker containers'
  inputs:
    script: docker ps
  condition: always()

# Step 5: Wait for the Django application to be ready
- task: CmdLine@2
  displayName: 'Check if Django application is ready'
  inputs:
    script: |
      echo Waiting for the Django application to be ready...
      for /l %%i in (1,1,10) do (
        curl -s -o nul -w "%%{http_code}" http://localhost:8000/admin | findstr 200 >nul
        if not errorlevel 1 (
          echo Server is up!
          exit /b 0
        )
        echo Retrying in 5 seconds...
        timeout /t 5 >nul
      )
      exit /b 1

# Step 6: Test the Django app
- task: CmdLine@2
  displayName: 'Test Django application'
  inputs:
    script: |
      curl -X POST http://localhost:8000/api/students/ ^
        -H "Content-Type: application/json" ^
        -d "{\"name\": \"Test Student\", \"age\": 21, \"course\": \"Computer Science\"}"

# Step 7: Stop and remove the Docker container
- task: CmdLine@2
  displayName: 'Stop and remove Django container'
  inputs:
    script: docker stop django-student-container && docker rm django-student-container
  condition: always()
