pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
    }

    stages {
        stage('Clone Repository') {
            steps {
                echo "Code cloned from GitHub automatically."
            }
        }

        stage('Set up Python Environment') {
            steps {
                bat 'python -m venv %VENV_DIR%'
                bat '%VENV_DIR%\\Scripts\\activate.bat && python -m pip install --upgrade pip'
                bat '%VENV_DIR%\\Scripts\\activate.bat && pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                bat '%VENV_DIR%\\Scripts\\activate.bat && python manage.py test --verbosity=2'
            }
        }
    }

    post {
        always {
            echo 'Test Pipeline Finished'
        }
        success {
            echo 'Tests Passed 🎉'
        }
        failure {
            echo 'Tests Failed ❌'
        }
    }
}
