trigger:
- main

pool:
  name: Default

steps:
# Step 1: Checkout code from GitHub
- checkout: self
  displayName: 'Checkout code from GitHub'

# Step 3: Build Docker image for Django (from dockerfile directory)
- task: CmdLine@2
  displayName: 'Build Docker image for Django'
  inputs:
    script: |
      cd C:\Users\asmika\DevopsPract\Student_MGT\dockerfile
      docker build -t django-student .

# Step 4: Run Docker container
- task: CmdLine@2
  displayName: 'Run Docker container now'
  inputs:
    script: docker run -d -p 8082:8000 --name django-student-container django-student

# Step 5: List running Docker containers
- task: CmdLine@2
  displayName: 'List running Docker containers'
  inputs:
    script: docker ps
  condition: always()

# Step 6: Wait for the Django application to be ready
- task: CmdLine@2
  displayName: 'Check if Django application is ready'
  inputs:
    script: |
      echo Waiting for the Django application to be ready...
      setlocal ENABLEDELAYEDEXPANSION
      for /L %%i in (1,1,10) do (
        echo Attempt %%i: Checking if the server is up...
        for /f "tokens=* usebackq" %%A in (`curl -s -o nul -w "%%{http_code}" http://localhost:8082/admin`) do (
          set "code=%%A"
        )
        if "!code!"=="200" (
          echo Server is up with HTTP code !code!
          exit /b 0
        )
        echo Server not ready yet (HTTP code: !code!), retrying in 5 seconds...
        timeout /t 5 >nul
      )
      echo Failed to connect to the server after multiple attempts.
      exit /b 1

# Step 7: Test the Django app with POST request
- task: CmdLine@2
  displayName: 'Test Django application'
  inputs:
    script: |
      curl -X POST http://localhost:8082/api/students/ ^
        -H "Content-Type: application/json" ^
        -d "{\"name\": \"Test Student\", \"age\": 21, \"course\": \"Computer Science\"}"

# Step 8: Stop and remove the Docker container
- task: CmdLine@2
  displayName: 'Stop and remove Django container'
  inputs:
    script: docker stop django-student-container && docker rm django-student-container
  condition: always()
